version: "3"

services:
    db:
        image: mysql:8.0
        container_name: database_ludycom
        restart: always
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql